---
title: "Getting R2"
output:
  html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rr2)
library(caper)
library(phylolm)
library(nlme)
library(ggplot2)
```

## Following Julien's steps with caper

```{r}
pglspirateMCC <- readRDS('/Users/acas/Dropbox/Post-docs/Morlon_Lab/manuscript_projects_info/mammals_genDiv_SpRate/manuscript_scripts_data/pgls/extra/pglsPispRateMCC.rds')
summary(pglspirateMCC)

ols <- lm(log(pglspirateMCC$data$data$EstPi) ~ log(pglspirateMCC$data$data$tipRate))
summary(ols)

ggplot(pglspirateMCC$data$data, aes(y = log(EstPi), x = log(tipRate))) + 
  geom_point() +
  geom_abline(aes(intercept=ols$coefficients['(Intercept)'], 
              slope=ols$coefficients['log(pglspirateMCC$data$data$tipRate)'],
              color = "PGLS"), size = 1) + 
  geom_abline(aes(intercept=pglspirateMCC$model$coef["(Intercept)"], 
              slope=pglspirateMCC$model$coef["log(tipRate)"], 
              color = "OLS"), size = 1) + 
  theme_bw() + labs(x = "Logged tip speciation rates", y = "Logged genetic diversity",
                    color = "Legend") 

#redpglspirateMCC <- pgls(log(EstPi) ~ 1, data = pglspirateMCC$data, lambda = 'ML')
#saveRDS(redpglspirateMCC, '/Users/acas/Dropbox/Post-docs/Morlon_Lab/manuscript_projects_info/mammals_genDiv_SpRate/manuscript_scripts_data/pgls/extra/redpglspirateMCC.rds')
redpglspirateMCC <- readRDS('/Users/acas/Dropbox/Post-docs/Morlon_Lab/manuscript_projects_info/mammals_genDiv_SpRate/manuscript_scripts_data/pgls/extra/redpglspirateMCC.rds')
summary(redpglspirateMCC)

#i) Take the “lambda” parameter estimated for your regression model and transform the tree according to it
#a.For instance: 
tree.full <- geiger::rescale(pglspirateMCC$data$phy, 
                     model='lambda', lambda=pglspirateMCC$param["lambda"]) 

#b.Then you can estimate a 'scaling' factor from the branch lengths (so that the branch lengths sum to 1 if you scale the tree, following Ives' paper):
scale.full <- sum(tree.full$edge.length)

#ii)Re-fit the model with an intercept only and do the same as above:
tree.reduced <- geiger::rescale(redpglspirateMCC$data$phy, model='lambda',
                                lambda=redpglspirateMCC$param["lambda"])
scale.red <- sum(tree.reduced$edge.length)

#iii)Now you can compute the R squared from the ‘scaling factors’ estimated above and sigma^2 estimated for both the complete and reduced model:
R2 <- 1 - (scale.full*summary(pglspirateMCC)$sigma^2)/(scale.red*summary(redpglspirateMCC)$sigma^2)

R2
```

## Rerunning pgls with phylolm to use rr2

```{r}
tr <- pglspirateMCC$data$phy
dt <- pglspirateMCC$data$data 
z.x <- phylolm(log(EstPi) ~ 1, phy = tr, data = dt, model = 'lambda')
summary(z.x)
lam.x <- round(z.x$optpar, digits = 4)
z.f <- phylolm(log(EstPi) ~ log(tipRate), phy = tr, data = dt, model = 'lambda')
summary(z.f)
z.v <- lm(log(EstPi) ~ log(tipRate), data = dt)

R2(z.f, z.x, phy = tr, pred = FALSE)
R2(z.f, z.v, phy = tr, pred = FALSE)
R2(z.f, phy = tr, pred = FALSE)
```

